//
//  ModelsViewController.swift
//  HorizonXS
//
//  Created by Carlos Jimenez on 9/21/19.
//  Copyright (c) 2019 Carlos Jimenez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ModelsDisplayLogic: class {
    func displaySomething(viewModel: Models.ViewModel)
}

class ModelsViewController: UITableViewController, ModelsDisplayLogic {
    var interactor: ModelsBusinessLogic?
    var router: (NSObjectProtocol & ModelsRoutingLogic & ModelsDataPassing)?

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }

    // MARK: Do something

    //@IBOutlet weak var nameTextField: UITextField!

    func doSomething() {
        interactor?.getModels()
    }

    func displaySomething(viewModel: Models.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
