//
//  ModelsViewController.swift
//  HorizonXS
//
//  Created by Carlos Jimenez on 9/21/19.
//  Copyright (c) 2019 Carlos Jimenez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ModelsDisplayLogic: class {
    func displayModels(viewModel: Models.ViewModel)
    func displayLoading()
    func hideLoading()
    func displayError(msg: String)
    func hideError()
    func showModel()
}

class ModelsViewController: UITableViewController {
    var interactor: ModelsBusinessLogic?
    var router: (NSObjectProtocol & ModelsRoutingLogic & ModelsDataPassing)?

    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
    }
}

extension ModelsViewController: ModelsDisplayLogic {
    func displayModels(viewModel: Models.ViewModel) {

    }

    func displayLoading() {

    }

    func hideLoading() {

    }

    func displayError(msg: String) {

    }

    func hideError() {

    }

    func showModel() {

    }

}
