//
//  ModelsInteractorTests.swift
//  HorizonXS
//
//  Created by Carlos Jimenez on 9/21/19.
//  Copyright (c) 2019 Carlos Jimenez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import HorizonXS
import XCTest

// swiftlint:disable all
class ModelsInteractorTests: XCTestCase {
    // MARK: Subject under test

    var sut: ModelsInteractor!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupModelsInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupModelsInteractor() {
        sut = ModelsInteractor()
    }

    // MARK: Test doubles

    class ModelsPresentationLogicSpy: ModelsPresentationLogic {
        var presentSomethingCalled = false

        func presentSomething(response: Models.Response) {
            presentSomethingCalled = true
        }
    }

    // MARK: Tests

    func testDoSomething() {
        // Given
        let spy = ModelsPresentationLogicSpy()
        sut.presenter = spy
        let request = Models.Request()

        // When
        sut.doSomething(request: request)

        // Then
        XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
    }
}
