//
//  ModelsWorkerTests.swift
//  HorizonXS
//
//  Created by Carlos Jimenez on 9/21/19.
//  Copyright (c) 2019 Carlos Jimenez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import HorizonXS
import XCTest

// swiftlint:disable all
class ModelsWorkerTests: XCTestCase {
    // MARK: Subject under test

    var sut: ModelsWorker!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupModelsWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupModelsWorker() {
        sut = ModelsWorker()
    }

    // MARK: Test doubles

    // MARK: Tests

    func testSomething() {
        // Given

        // When

        // Then
    }
}
