//
//  ModelsWorkerTests.swift
//  HorizonXS
//
//  Created by Carlos Jimenez on 9/21/19.
//  Copyright (c) 2019 Carlos Jimenez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import HorizonXS
import XCTest

// swiftlint:disable all
class ModelsWorkerTests: XCTestCase {
    // MARK: Subject under test

    var sut: ModelsWorker!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupModelsWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Get File
    func loadResponse() -> ModelsEntity? {
        let bundle = Bundle(for: ModelsWorkerTests.classForCoder())
        let jsonFile =  bundle.path(forResource: "get_models_200", ofType: "json")
        let data = try? Data(contentsOf: URL(fileURLWithPath: jsonFile!), options: [])
        let serialized = try? JSONDecoder().decode(ModelsEntity.self, from: data!)
        return serialized
    }

    // MARK: Test setup

    func setupModelsWorker() {
        sut = ModelsWorker()
    }

    // MARK: Test doubles

    // MARK: Tests
    func testFetchModels() {
        //Given
        ModelsStubs().enableStubs()
        var response: ModelsEntity?
        let expected = loadResponse()
        let expectation = self.expectation(description: "Fetch models")

        //When
        sut.fetchModels(manufacturer: "000", page: 0) { result in
            switch result {
            case .success(let data):
                response = data
            default:
                break
            }
            expectation.fulfill()
        }

        //Then
        waitForExpectations(timeout: 1, handler: nil)
        XCTAssertNotNil(response)
        XCTAssertEqual(response, expected)
    }

    func testErrorFetchModels() {
        //Given
        ModelsStubs().enableErrorStubs()
        var response: XSError?
        let expected = XSError.unknown
        let expectation = self.expectation(description: "Fetch models")

        //When
        sut.fetchModels(manufacturer: "123", page: 0) { result in
            switch result {
            case .failure(let error):
                response = error
            default:
                break
            }
            expectation.fulfill()
        }

        //Then
        waitForExpectations(timeout: 1, handler: nil)
        XCTAssertNotNil(response)
        XCTAssertEqual(response, expected)
    }

    func testWrongFetchModels() {
        //Given
        ModelsStubs().enableWrongStubs()
        var response: XSError?
        let expected = XSError.responseSerialization
        let expectation = self.expectation(description: "Fetch models")

        //When
        sut.fetchModels(manufacturer: "1337", page: 0) { result in
            switch result {
            case .failure(let error):
                response = error
            default:
                break
            }
            expectation.fulfill()
        }

        //Then
        waitForExpectations(timeout: 1, handler: nil)
        XCTAssertNotNil(response)
        XCTAssertEqual(response, expected)
    }
}
